### ISSUE TITLE
Logger Implementation

### ISSUE THREAD

**Issue by jaihon1** [jgsimard/big-dreamer#2]
- [x] Cleanup Logger
- [x] Integrate Wandb to Logger class

**Comment by etho44** [comment]
Questions/comments: 

- Do we want to log training metrics or just evaluation?
- Should the step given to the logger in line 222 of main.py be train_step instead of env_steps?
- I put some env.close() after each rollout loops parce que ça poppait pleins de windows qui se ferment pas. Idéalement on devrait turn off the rendering du gym env.
